### PR TITLE
Added Hand Segmentation model

### PR DESCRIPTION
**Pull request by Kushagra-awasthi**
Hand Segmentation model added to the application_model_zoo.

### CODE REVIEW

**Comment by THEFASHIONGEEK** [comment]
Thank you for the tutorial. 
1. Please remove the absolute colab paths.
2. Check out this error
image

**Comment by abhi-kumar** [comment]
Further changes to be made
a) Replace gdirve link to dataset with original link 
b) Mention steps to reproduce formatted dataset

**Comment by Kushagra-awasthi** [comment]
@THEFASHIONGEEK the following two issues mentioned by you are resolved please check and let me know if any more changes are to be made.

**Comment by abhi-kumar** [comment]
The tutorial has been merged with the main repo. Old jupyter notebook for the same (included in the merge) has been removed.

Thank you for adding this tutorial to the model zoo, your efforts are greatly appreciated.

**Pull request merged**
